# Generated by Django 2.2.4 on 2020-06-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
